namespace :add_dimensions_to_products do
  desc "TODO"
  task :start => :environment do
    Product.all.each do |product|
      product.update_attributes(height: rand(5) + 1, width: rand(9) + 1, 
                                length: rand(13) + 1, weight: rand(10) + 1)
    end
  end
end
#this file generated by rails g task add_dimensions_to_products start